services:
  - type: web
    name: cardiocare-ai
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: "3.11.11"